---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

env:
  global:
    - ANSIBLE_ROLES_PATH=$TRAVIS_BUILD_DIR/../

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - ln -s $TRAVIS_BUILD_DIR ${TRAVIS_BUILD_DIR%/*}/sysfs
  # Install ansible and ansible-lint
  - pip install ansible ansible-lint
  # Check ansible version
  - ansible --version
  - ansible-lint --version

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # Linter
  - ansible-lint tests/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
