---

- name: create configuration file for sysfsutils
  copy:
    src: sysfs.conf
    dest: /etc/sysfs.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
    - restart sysfsutils

- name: create configuration directory for sysfsutils
  file:
    path: /etc/sysfs.d
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  notify:
    - restart sysfsutils

- name: crate init-script for sysfsutils
  copy:
    src: sysfsutils.redhat.init
    dest: /etc/init.d/sysfsutils
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  notify:
    - restart sysfsutils
